#!/usr/bin/env bash
#
subdomains_list=(www lb-01 web-01 web-02)
if [ "$#" -eq 1 ]
then
    for i in "${subdomains_list[@]}"
    do
        dig "$i"."$1" | grep -e ^"$i" | awk '{print "The subdomain '"$i"' is a", $4, "record and points to", $5}'
    done
elif [ "$#" -eq 2 ]
then
    dig "$2"."$1" | grep -e ^"$2" | awk '{print "The subdomain '"$2"' is a", $4, "record and points to", $5}'
fi

