#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# write a Bash script that configures a new Ubuntu machine to respect above requirements
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx start
