#!/usr/bin/env bash
# displays ans infinity and beyond
# I am invincible!!! when receiving a SIGTERM signal
trap "echo 'I am invincible!!!'" SIGTERM
while :;
do
    echo "To infinity and beyond";
    sleep 2;
done
