#!/usr/bin/env bash
#Write a Bash script that displays:
#The content of the current directory, in a list format
FILE="Holbertonschool"

if [ -e $FILE ]
then
    echo "holbertonschool file exists"
    if [ -s $FILE ]
    then
        echo "holbertonschool file is not empty"
    else
        echo "holbertonschool file is empty"
    fi
    if [ -f $FILE ]
    then
        echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
